---
title: <center>Community AMARETTO Report</center>
output: 
  html_document:
    theme: cerulean
    highlight: NULL
---

<center>


## Run Information
<br><br><br>
```{r RunInfo,echo=FALSE}
datatable(RunInfo,class = "display",escape=FALSE,rownames = FALSE)
```
<br><br><br>

## Community Network
<br><br><br>
```{r network,echo=FALSE}
Nodes_Mnetwork<-igraph::as_data_frame(cAMARETTOnetworkM$module_network,what="vertices")

plot(cAMARETTOnetworkC$CommGraph,layout=cAMARETTOnetworkM$layoutMN,
       vertex.color=as.character(Nodes_Mnetwork$color),
       vertex.label=NA,
       vertex.frame.color=NA,
       edge.color="gray80",
       mark.groups = cAMARETTOnetworkC$community_list,
       mark.col=cAMARETTOnetworkC$color_list,
       mark.border=NA)

legend(x = -1.5, y = -1.1+0.05*length(cAMARETTOnetworkM$colMN), legend = names(cAMARETTOnetworkM$colMN), col = cAMARETTOnetworkM$colMN, pch=19, bty="n",ncol=ceiling(length(cAMARETTOnetworkM$colMN)/5))
legend(x = 1.1, y = 1.5, legend=names(cAMARETTOnetworkC$color_list), col=cAMARETTOnetworkC$color_list, pch=19, bty="n",cex=max(0.9,1/(1+0.02*length(cAMARETTOnetworkC$color_list))),ncol=ceiling(length(cAMARETTOnetworkC$color_list)/15))
```
<br><br><br>

## Assignments of Modules to Communities
<br><br><br>
```{r CommunityModules,echo=FALSE}
datatable(ComModulesLink %>% 
            dplyr::rename(Edges="numTotalEdgesInCommunity","Fraction Edges"="fractEdgesInVsOut","Fraction Size"="CommsizeFrac"), class = "display",
          extensions = "Buttons",
          rownames = FALSE,
          options = list(pageLength = 10, 
                         dom = "Bfrtip", 
                         scrollX=TRUE,
                         scrollY=1000,
                        scrollCollapse= FALSE,
                        paging = TRUE,
                        lengthChange = FALSE,
                         buttons = list(list(extend = 'csv',text = "Save CSV", title="ComModuleRelation"))),
          escape=FALSE) %>%
          formatSignif(c("Fraction Edges","Fraction Size"),2)
```
<br><br><br>

## Assignments of Driver Genes to Communities
<br><br><br>
```{r CommunityDrivers,echo=FALSE}
DTComDrivers
```
<br><br><br>


## Assignments of Genes to Communities
<br><br><br>
```{r CommunityGenes, echo=FALSE}
datatable(GeneComLink, class = "display",
          extensions = "Buttons",
          rownames = FALSE,
          options = list(pageLength = 10,
                         autoWidth = TRUE,
                         columnDefs = list(list(width = '50px', targets = "_all")),
                         dom = "Bfrtip", 
                         buttons = list(list(extend = 'csv',text = "Save CSV", title="ComGeneRelation"))),
          escape=FALSE)
```
<br><br><br>

## Enrichments of Functional Categories in Communities
<br><br><br>
```{r DTGSEAall, echo=FALSE}
DTGSEAall
```
<br><br><br>

## Phenotype Association Table of Communities
<br><br><br>
```{r CommunityDTPhC,echo=FALSE}
DTPh
```
<br><br><br>

</center>